# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lctrl.xdc

# IP: ip/De24_0/De24_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==De24_0 || ORIG_REF_NAME==De24_0} -quiet] -quiet
