set_property SRC_FILE_INFO {cfile:D:/OLab/Lab0/LED_Decoder/LED_Decoder.srcs/constrs_1/new/lctrl.xdc rfile:../../../LED_Decoder.srcs/constrs_1/new/lctrl.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AA10  IOSTANDARD LVCMOS15 } [get_ports {sw[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AB10  IOSTANDARD LVCMOS15 } [get_ports {sw[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W23  IOSTANDARD LVCMOS33 } [get_ports {LED[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AB26  IOSTANDARD LVCMOS33 } [get_ports {LED[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y25  IOSTANDARD LVCMOS33 } [get_ports {LED[2]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AA23  IOSTANDARD LVCMOS33 } [get_ports {LED[3]}]
